###########################
# Theme (TokyoNight Storm default)
###########################
set -g status-style "bg=#1f2335,fg=#c0caf5"
set -g message-style "bg=#24283b,fg=#c0caf5"
set -g message-command-style "bg=#24283b,fg=#7aa2f7"
set -g pane-border-style "fg=#1f2335,bg=#1f2335"
set -g pane-active-border-style "fg=#1f2335,bg=#1f2335"
set -g mode-style "bg=#7aa2f7,fg=#1f2335"
set -g window-status-style "bg=#1f2335,fg=#a9b1d6"
set -g window-status-current-style "bg=#24283b,fg=#7aa2f7"
set -g window-status-activity-style "bg=#1f2335,fg=#e0af68"
