# Usage: `brew bundle --file Brewfile`

brew 'rcm'
brew 'coreutils'
brew 'grep'
brew 'git'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'neovim'
brew 'ripgrep'
brew 'bat'

cask 'mattr-slate'
cask 'mimestream'
cask 'linear-linear'
cask 'figma'
cask 'obsidian'
cask 'logseq'
cask 'portfolioperformance'
cask 'kitty'
cask 'alfred'
cask 'fork'
cask 'slack'
cask '1password'
cask 'spotify'
cask 'eloston-chromium'
cask 'calibre'
cask 'lens'
