#!/bin/sh

# Map nvim config file to standard vim location
if [ ! -e $HOME/.config/nvim/init.vim ]; then
  [ ! -e $HOME/.config/nvim ] && mkdir -p $HOME/.config/nvim

  cat <<EOF >$HOME/.config/nvim/init.vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF
fi

# Prepare .z file so that it doesn't create an error on first jump
[ ! -e $HOME/.z ] && touch $HOME/.z

if [ ! -e $HOME/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -e $HOME/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.0
  asdf plugin-add nodejs
  export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && mkdir -p "$GNUPGHOME" && chmod 0700 "$GNUPGHOME"
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
fi
